name: Azure Automation Upload and Compile
on:
  workflow_dispatch:
  ## events used later for logic that selets to deploy to QA, Prod targets
  release:
    types: [prereleased, released]
  ## events used later for logic that selets to deploy to PoC, Dev destinations
  push:
    branches-ignore:
      - 'NoTrigger**'
    ##paths:
      ##- 'dcMonitor/*.ps1'
      ##- 'dcManufacturing/*.ps1'

permissions:
  id-token: write
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  DoTheDo:
    name: Checkout the Repo
    environment:
      ## name: ${{ github.event_name == 'release' && ( github.event.release.prerelease == true && 'QA' || 'Prod' ) || (github.ref_name == 'main' && 'Dev' || 'poc') }}
      name: 'poc'

    runs-on: ubuntu-latest

    steps:
      - name: Check it out!
        uses: actions/checkout@v4

      - name: Connect to Azure for the AZ subscription specified by secrets/vars for _this_ GitHub Deployment Environment
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Upload and Compile Changed DSC Code
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
           #Export out all MVP* DSC Configurations and rename them to remove the leading \ character that stupid Microsoft adds
           $dirSeparator = [IO.Path]::DirectorySeparatorChar
           New-Item -Type Directory -Name "temp" -Path $env:GITHUB_WORKSPACE
           $tempDSCFilePath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath ("temp" + $dirSeparator)
           $repoDSCFileLocation = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath ("DSC" + $dirSeparator + "*.ps1")
           @'
            ${{ vars.AZURE_AUTOMATION_ACCOUNTS }}
           '@ | ConvertFrom-Json
           
           @'
           ${{ vars.REPO_TRIGGER_FOLDERS }}
           '@ | ConvertFrom-Json